name: Daily News, Crypto, and Anomaly Update

on:
  schedule:
    - cron: '0 * * * *' # Berjalan tiap 1 jam
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib beautifulsoup4 requests lxml plotly yfinance
      - name: Run Full Data Pipeline
        run: |
          # Masuk ke folder scripts untuk jalankan mesin data
          cd scripts
          python main.py
          # Kembali ke root agar visualizer bisa simpan dashboard.html di tempat yang benar
          cd ..
          python visualizer.py

      - name: Commit and Push All Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 1. Daftarkan semua file hasil generate Python (PENTING!)
          git add .
          
          # 2. Ambil perubahan dari server (jika ada) tanpa bentrok
          git pull origin main --rebase
          
          # 3. Commit dan Push
          git commit -m "Automated Data Update: All Projects [skip ci]" || echo "No changes to commit"
          git push origin main
